LOCALES = ("en", "ru")
DEFAULT_LOCALE = "en"


STRINGS: dict[str, dict[str, str]] = {
    "welcome_title": {
        "en": "<b>Document Assistant</b>",
        "ru": "<b>Документный ассистент</b>",
    },
    "welcome": {
        "en": """<b>Document Assistant</b>

Upload a PDF, DOCX, or TXT document and ask questions about its content. Answers include numbered citations to the source passages.

<b>Commands</b>
/list — indexed documents
/settings — language and account
/reset — delete all data
/help — usage guide

Max file size: {max_file_mb} MB""",
        "ru": """<b>Документный ассистент</b>

Загрузите PDF, DOCX или TXT-документ и задавайте вопросы по его содержимому. Ответы включают нумерованные ссылки на исходные фрагменты.

<b>Команды</b>
/list — индексированные документы
/settings — язык и учетная запись
/reset — удалить все данные
/help — руководство

Максимальный размер файла: {max_file_mb} МБ""",
    },
    "help": {
        "en": """<b>Usage</b>

<b>1. Upload a document.</b> Send any PDF, DOCX, or TXT file (up to {max_file_mb} MB). The bot extracts the text, splits it into chunks, and indexes them with local embeddings.

<b>2. Ask a question.</b> Send a plain text message. The bot retrieves the most relevant chunks and answers using only their content. Every claim is cited with <code>[N]</code> pointing to a numbered source.

<b>3. Manage your data.</b> Use /list to view indexed documents, /settings to change language or delete data, and /reset to remove everything in one step.

<b>Notes</b>
• Each user's data is isolated — you only see your own documents.
• Embeddings run locally on CPU. No content is sent to embedding services.
• Answers are generated by an LLM and may be incomplete; verify against the cited sources.""",
        "ru": """<b>Использование</b>

<b>1. Загрузите документ.</b> Отправьте PDF, DOCX или TXT-файл (до {max_file_mb} МБ). Бот извлечет текст, разделит его на фрагменты и проиндексирует локальными эмбеддингами.

<b>2. Задайте вопрос.</b> Отправьте обычное текстовое сообщение. Бот найдет наиболее релевантные фрагменты и ответит только на основе их содержимого. Каждое утверждение сопровождается ссылкой <code>[N]</code> на нумерованный источник.

<b>3. Управляйте данными.</b> Используйте /list для просмотра документов, /settings для смены языка или удаления данных, и /reset для удаления всего за один шаг.

<b>Примечания</b>
• Данные каждого пользователя изолированы — вы видите только свои документы.
• Эмбеддинги выполняются локально на CPU. Контент не отправляется в сервисы эмбеддингов.
• Ответы генерируются LLM и могут быть неполными; сверяйтесь с источниками.""",
    },
    "processing": {
        "en": "⏳ Processing <code>{filename}</code>…",
        "ru": "⏳ Обработка <code>{filename}</code>…",
    },
    "indexed": {
        "en": "✅ Indexed <code>{filename}</code>\n{chunk_count} chunks · ready for queries",
        "ru": "✅ Проиндексирован <code>{filename}</code>\n{chunk_count} фрагментов · готов к запросам",
    },
    "upload_error": {
        "en": "❌ <code>{filename}</code>\n{error_reason}",
        "ru": "❌ <code>{filename}</code>\n{error_reason}",
    },
    "error_unsupported_format": {
        "en": "Unsupported format. Send PDF, DOCX, or TXT.",
        "ru": "Формат не поддерживается. Отправьте PDF, DOCX или TXT.",
    },
    "error_no_text": {
        "en": "No extractable text found in this document.",
        "ru": "В документе не найден извлекаемый текст.",
    },
    "error_too_large": {
        "en": "Exceeds {max_file_mb} MB limit.",
        "ru": "Превышен лимит {max_file_mb} МБ.",
    },
    "answer_message": {
        "en": "<b>Answer</b>\n{answer}\n\n<blockquote expandable><b>Sources</b>\n{sources}\n</blockquote>",
        "ru": "<b>Ответ</b>\n{answer}\n\n<blockquote expandable><b>Источники</b>\n{sources}\n</blockquote>",
    },
    "answer_not_found": {
        "en": "<i>I could not find this in your documents.</i>",
        "ru": "<i>Не удалось найти это в ваших документах.</i>",
    },
    "source_line": {
        "en": "[{number}] <code>{filename}</code> · chunk {idx}",
        "ru": "[{number}] <code>{filename}</code> · фрагмент {idx}",
    },
    "rate_limited": {
        "en": "⚠️ The free language model is currently rate-limited.\n\nPlease retry in a moment, or set your own OpenRouter API key for higher limits.",
        "ru": "⚠️ Бесплатный лимит языковой модели исчерпан.\n\nПовторите запрос через минуту или укажите собственный ключ OpenRouter для более высоких лимитов.",
    },
    "list_empty": {
        "en": "<b>Your documents</b>\n\n<i>No documents yet. Send a file to get started.</i>",
        "ru": "<b>Ваши документы</b>\n\n<i>Документов пока нет. Отправьте файл, чтобы начать.</i>",
    },
    "list_header": {
        "en": "<b>Your documents</b>",
        "ru": "<b>Ваши документы</b>",
    },
    "list_item": {
        "en": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} chunks</i>",
        "ru": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} фрагментов</i>",
    },
    "settings": {
        "en": "<b>Settings</b>\n\nLanguage: <b>{locale_name}</b>\nDocuments: <b>{doc_count}</b>\nChunks: <b>{chunk_count}</b>",
        "ru": "<b>Настройки</b>\n\nЯзык: <b>{locale_name}</b>\nДокументы: <b>{doc_count}</b>\nФрагменты: <b>{chunk_count}</b>",
    },
    "reset_confirm": {
        "en": "<b>Delete all your data?</b>\n\nThis removes {doc_count} documents and {chunk_count} chunks. The action cannot be undone.",
        "ru": "<b>Удалить все ваши данные?</b>\n\nБудет удалено документов: {doc_count}, фрагментов: {chunk_count}. Действие нельзя отменить.",
    },
    "reset_done": {
        "en": "✅ All data removed.",
        "ru": "✅ Все данные удалены.",
    },
    "delete_confirm": {
        "en": "<b>Delete this document?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} chunks</i>",
        "ru": "<b>Удалить этот документ?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} фрагментов</i>",
    },
    "locale_name_en": {
        "en": "English",
        "ru": "Английский",
    },
    "locale_name_ru": {
        "en": "Russian",
        "ru": "Русский",
    },
    "button_english": {
        "en": "🇬🇧 English",
        "ru": "🇬🇧 English",
    },
    "button_russian": {
        "en": "🇷🇺 Русский",
        "ru": "🇷🇺 Русский",
    },
    "button_settings": {
        "en": "Settings",
        "ru": "Настройки",
    },
    "button_delete_all": {
        "en": "Delete all data",
        "ru": "Удалить все данные",
    },
    "button_close": {
        "en": "Close",
        "ru": "Закрыть",
    },
    "button_yes_delete": {
        "en": "Yes, delete everything",
        "ru": "Да, удалить все",
    },
    "button_cancel": {
        "en": "Cancel",
        "ru": "Отмена",
    },
    "button_delete_document": {
        "en": "🗑 {filename}",
        "ru": "🗑 {filename}",
    },
    "button_confirm": {
        "en": "Confirm",
        "ru": "Подтвердить",
    },
}


def t(key: str, locale: str = DEFAULT_LOCALE, **kwargs) -> str:
    """Lookup a string for a locale. Substitute kwargs via str.format."""
    template = (
        STRINGS.get(key, {}).get(locale)
        or STRINGS.get(key, {}).get(DEFAULT_LOCALE)
        or key
    )
    if kwargs:
        return template.format(**kwargs)
    return template
