LOCALES = ("en", "ru", "es", "de", "fr", "zh", "pt")
DEFAULT_LOCALE = "en"


STRINGS: dict[str, dict[str, str]] = {
    "welcome_title": {
        "en": "<b>Document Assistant</b>",
        "ru": "<b>Документный ассистент</b>",
        "es": "<b>Asistente de Documentos</b>",
        "de": "<b>Dokumenten-Assistent</b>",
        "fr": "<b>Assistant Documents</b>",
        "zh": "<b>文档助手</b>",
        "pt": "<b>Assistente de Documentos</b>",
    },
    "welcome": {
        "en": """<b>Document Assistant</b>

Upload a PDF, DOCX, or TXT file and ask questions about it. The bot answers only from your documents and shows numbered source citations.

Your files are stored locally for your Telegram account. Embeddings run locally; only the most relevant text fragments are sent to the configured LLM provider to generate an answer. You can delete one document from /list or wipe everything with /reset.

<b>Commands</b>
/list — indexed documents
/settings — language and account
/privacy — how document data is handled
/brief — executive summary
/faq — questions and answers
/quiz — interactive quiz
/mindmap — topic map
/reset — delete all data
/help — usage guide

Max file size: {max_file_mb} MB""",
        "ru": """<b>Документный ассистент</b>

Загрузите PDF, DOCX или TXT-документ и задавайте вопросы по его содержимому. Ответы включают нумерованные ссылки на исходные фрагменты.

<b>Команды</b>
/list — индексированные документы
/settings — язык и учётная запись
/privacy — как обрабатываются документы
/brief — краткий бриф
/faq — вопросы и ответы
/quiz — интерактивный тест
/mindmap — карта тем
/reset — удалить все данные
/help — руководство

Максимальный размер файла: {max_file_mb} МБ""",
        "es": """<b>Asistente de Documentos</b>

Sube un documento PDF, DOCX o TXT y formula preguntas sobre su contenido. Las respuestas incluyen citas numeradas a los fragmentos de origen.

<b>Comandos</b>
/list — documentos indexados
/settings — idioma y cuenta
/reset — eliminar todos los datos
/help — guía de uso

Tamaño máximo del archivo: {max_file_mb} MB""",
        "de": """<b>Dokumenten-Assistent</b>

Laden Sie eine PDF-, DOCX- oder TXT-Datei hoch und stellen Sie Fragen zu deren Inhalt. Antworten enthalten nummerierte Zitate zu den Quellpassagen.

<b>Befehle</b>
/list — indexierte Dokumente
/settings — Sprache und Konto
/reset — alle Daten löschen
/help — Bedienungsanleitung

Maximale Dateigröße: {max_file_mb} MB""",
        "fr": """<b>Assistant Documents</b>

Téléversez un document PDF, DOCX ou TXT et posez des questions sur son contenu. Les réponses incluent des citations numérotées vers les passages sources.

<b>Commandes</b>
/list — documents indexés
/settings — langue et compte
/reset — supprimer toutes les données
/help — guide d'utilisation

Taille maximale du fichier : {max_file_mb} Mo""",
        "zh": """<b>文档助手</b>

上传 PDF、DOCX 或 TXT 文档，并就其内容提问。回答中包含指向原文段落的编号引用。

<b>命令</b>
/list — 已索引的文档
/settings — 语言和账户
/reset — 删除所有数据
/help — 使用指南

最大文件大小：{max_file_mb} MB""",
        "pt": """<b>Assistente de Documentos</b>

Envie um documento PDF, DOCX ou TXT e faça perguntas sobre o seu conteúdo. As respostas incluem citações numeradas para os trechos de origem.

<b>Comandos</b>
/list — documentos indexados
/settings — idioma e conta
/reset — excluir todos os dados
/help — guia de uso

Tamanho máximo do arquivo: {max_file_mb} MB""",
    },
    "help": {
        "en": """<b>Usage</b>

<b>1. Upload a document.</b> Send any PDF, DOCX, or TXT file (up to {max_file_mb} MB). The bot extracts the text, splits it into chunks, and indexes them with local embeddings.

<b>2. Ask a question.</b> Send a plain text message. The bot retrieves the most relevant chunks and answers using only their content. Every claim is cited with <code>[N]</code> pointing to a numbered source.

<b>3. Manage your data.</b> Use /list to view indexed documents, /settings to change language or delete data, and /reset to remove everything in one step.

<b>Notes</b>
• Each user's data is isolated — you only see your own documents.
• Embeddings run locally on CPU. No content is sent to embedding services.
• Answers are generated by an LLM and may be incomplete; verify against the cited sources.""",
        "ru": """<b>Использование</b>

<b>1. Загрузите документ.</b> Отправьте PDF, DOCX или TXT-файл (до {max_file_mb} МБ). Бот извлечёт текст, разделит его на фрагменты и проиндексирует локальными эмбеддингами.

<b>2. Задайте вопрос.</b> Отправьте обычное текстовое сообщение. Бот найдёт наиболее релевантные фрагменты и ответит только на основе их содержимого. Каждое утверждение сопровождается ссылкой <code>[N]</code> на нумерованный источник.

<b>3. Управляйте данными.</b> Используйте /list для просмотра документов, /settings для смены языка или удаления данных, и /reset для удаления всего за один шаг.

<b>Примечания</b>
• Данные каждого пользователя изолированы — вы видите только свои документы.
• Эмбеддинги выполняются локально на CPU. Контент не отправляется в сервисы эмбеддингов.
• Ответы генерируются LLM и могут быть неполными; сверяйтесь с источниками.""",
        "es": """<b>Uso</b>

<b>1. Sube un documento.</b> Envía cualquier archivo PDF, DOCX o TXT (hasta {max_file_mb} MB). El bot extrae el texto, lo divide en fragmentos y los indexa con embeddings locales.

<b>2. Formula una pregunta.</b> Envía un mensaje de texto. El bot recupera los fragmentos más relevantes y responde utilizando solo su contenido. Cada afirmación se cita con <code>[N]</code> apuntando a una fuente numerada.

<b>3. Gestiona tus datos.</b> Usa /list para ver los documentos indexados, /settings para cambiar el idioma o eliminar datos, y /reset para eliminar todo de una vez.

<b>Notas</b>
• Los datos de cada usuario están aislados — solo ves tus propios documentos.
• Los embeddings se ejecutan localmente en CPU. El contenido no se envía a servicios externos.
• Las respuestas son generadas por un LLM y pueden ser incompletas; verifica con las fuentes citadas.""",
        "de": """<b>Verwendung</b>

<b>1. Dokument hochladen.</b> Senden Sie eine PDF-, DOCX- oder TXT-Datei (bis zu {max_file_mb} MB). Der Bot extrahiert den Text, teilt ihn in Abschnitte und indexiert sie mit lokalen Embeddings.

<b>2. Frage stellen.</b> Senden Sie eine einfache Textnachricht. Der Bot ruft die relevantesten Abschnitte ab und antwortet nur anhand deren Inhalt. Jede Aussage wird mit <code>[N]</code> auf eine nummerierte Quelle verwiesen.

<b>3. Daten verwalten.</b> Verwenden Sie /list zum Anzeigen indexierter Dokumente, /settings zum Ändern der Sprache oder Löschen von Daten und /reset, um alles auf einmal zu entfernen.

<b>Hinweise</b>
• Die Daten jedes Benutzers sind isoliert — Sie sehen nur Ihre eigenen Dokumente.
• Embeddings werden lokal auf der CPU berechnet. Inhalte werden nicht an externe Dienste gesendet.
• Antworten werden von einem LLM generiert und können unvollständig sein; prüfen Sie sie anhand der zitierten Quellen.""",
        "fr": """<b>Utilisation</b>

<b>1. Téléversez un document.</b> Envoyez un fichier PDF, DOCX ou TXT (jusqu'à {max_file_mb} Mo). Le bot extrait le texte, le découpe en fragments et les indexe avec des embeddings locaux.

<b>2. Posez une question.</b> Envoyez un message texte. Le bot récupère les fragments les plus pertinents et répond uniquement à partir de leur contenu. Chaque affirmation est citée par <code>[N]</code> renvoyant à une source numérotée.

<b>3. Gérez vos données.</b> Utilisez /list pour voir les documents indexés, /settings pour changer la langue ou supprimer des données, et /reset pour tout supprimer en une étape.

<b>Notes</b>
• Les données de chaque utilisateur sont isolées — vous ne voyez que vos propres documents.
• Les embeddings sont calculés localement sur CPU. Aucun contenu n'est envoyé à des services externes.
• Les réponses sont générées par un LLM et peuvent être incomplètes ; vérifiez-les avec les sources citées.""",
        "zh": """<b>使用说明</b>

<b>1. 上传文档。</b>发送任意 PDF、DOCX 或 TXT 文件（最大 {max_file_mb} MB）。机器人会提取文本，将其切分为片段，并使用本地嵌入对其进行索引。

<b>2. 提出问题。</b>发送一条普通文本消息。机器人会检索最相关的片段，并仅基于其内容作答。每个论断都通过 <code>[N]</code> 引用对应的编号来源。

<b>3. 管理数据。</b>使用 /list 查看已索引的文档，使用 /settings 切换语言或删除数据，使用 /reset 一次性删除全部内容。

<b>说明</b>
• 每位用户的数据相互隔离——您只能看到自己的文档。
• 嵌入计算在本地 CPU 上完成，内容不会发送给外部嵌入服务。
• 回答由 LLM 生成，可能不完整；请对照引用的来源进行核实。""",
        "pt": """<b>Uso</b>

<b>1. Envie um documento.</b> Envie qualquer arquivo PDF, DOCX ou TXT (até {max_file_mb} MB). O bot extrai o texto, divide-o em trechos e os indexa com embeddings locais.

<b>2. Faça uma pergunta.</b> Envie uma mensagem de texto comum. O bot recupera os trechos mais relevantes e responde apenas com base no conteúdo deles. Cada afirmação é citada com <code>[N]</code> apontando para uma fonte numerada.

<b>3. Gerencie seus dados.</b> Use /list para ver os documentos indexados, /settings para alterar idioma ou excluir dados, e /reset para remover tudo de uma só vez.

<b>Notas</b>
• Os dados de cada usuário são isolados — você vê apenas seus próprios documentos.
• Os embeddings são executados localmente na CPU. O conteúdo não é enviado a serviços externos.
• As respostas são geradas por um LLM e podem estar incompletas; verifique nas fontes citadas.""",
    },
    "privacy": {
        "en": """<b>Privacy and security</b>

<b>What is stored</b>
Your uploaded document text, filenames, and local embeddings are stored in this bot's SQLite database and linked to your Telegram user ID.

<b>What leaves the bot</b>
Embeddings are created locally. When you ask a question, the bot sends your question plus the most relevant document fragments to the configured LLM provider through OpenRouter. Full files are not sent for every answer.

<b>Access control</b>
Searches and document lists are filtered by your Telegram user ID, so other users cannot query your indexed documents through the bot.

<b>Control</b>
Use /list to delete a single document, or /reset to delete all documents and chunks for your account.""",
        "ru": """<b>Приватность и безопасность</b>

<b>Что хранится</b>
Текст загруженных документов, имена файлов и локальные эмбеддинги хранятся в SQLite-базе этого бота и привязаны к вашему Telegram user ID.

<b>Что уходит наружу</b>
Эмбеддинги считаются локально. Когда вы задаёте вопрос, бот отправляет ваш вопрос и самые релевантные фрагменты документов в настроенного LLM-провайдера через OpenRouter. Полные файлы не отправляются для каждого ответа.

<b>Разделение доступа</b>
Поиск и список документов фильтруются по вашему Telegram user ID, поэтому другие пользователи не могут спрашивать бот по вашим индексированным документам.

<b>Контроль</b>
Используйте /list, чтобы удалить один документ, или /reset, чтобы удалить все документы и фрагменты для вашего аккаунта.""",
    },
    "studio_empty": {
        "en": "No indexed documents yet. Send a PDF, DOCX, or TXT file first.",
        "ru": "Пока нет индексированных документов. Сначала отправьте PDF, DOCX или TXT.",
    },
    "studio_working": {
        "en": "Preparing <b>{artifact}</b> for <code>{filename}</code>...",
        "ru": "Готовлю <b>{artifact}</b> для <code>{filename}</code>...",
    },
    "studio_error": {
        "en": "The LLM provider is rate-limited right now. The document is indexed; please try this action again in a moment.",
        "ru": "Сейчас сработал лимит LLM-провайдера. Документ уже проиндексирован; попробуйте это действие ещё раз через минуту.",
    },
    "artifact_overview": {
        "en": "overview",
        "ru": "обзор",
    },
    "artifact_brief": {
        "en": "brief",
        "ru": "бриф",
    },
    "artifact_faq": {
        "en": "FAQ",
        "ru": "FAQ",
    },
    "artifact_quiz": {
        "en": "quiz",
        "ru": "тест",
    },
    "artifact_mindmap": {
        "en": "mind map",
        "ru": "карту тем",
    },
    "studio_result": {
        "en": "<b>{title}</b>\n<code>{filename}</code>\n\n{body}",
        "ru": "<b>{title}</b>\n<code>{filename}</code>\n\n{body}",
    },
    "quiz_title": {
        "en": "<b>Quiz</b>\n<code>{filename}</code>\n\n<b>{number}/{total}.</b> {question}",
        "ru": "<b>Тест</b>\n<code>{filename}</code>\n\n<b>{number}/{total}.</b> {question}",
    },
    "quiz_correct": {
        "en": "Correct.",
        "ru": "Верно.",
    },
    "quiz_wrong": {
        "en": "Not quite. Correct answer: <b>{answer}</b>",
        "ru": "Не совсем. Правильный ответ: <b>{answer}</b>",
    },
    "quiz_answered": {
        "en": "<b>Quiz</b>\n<code>{filename}</code>\n\n<b>{number}/{total}.</b> {question}\n\n{result}\n\n{explanation} {citation}",
        "ru": "<b>Тест</b>\n<code>{filename}</code>\n\n<b>{number}/{total}.</b> {question}\n\n{result}\n\n{explanation} {citation}",
    },
    "quiz_done": {
        "en": "<b>Quiz complete</b>\nYou finished all questions for <code>{filename}</code>.",
        "ru": "<b>Тест завершён</b>\nВы ответили на все вопросы по <code>{filename}</code>.",
    },
    "processing": {
        "en": "⏳ Processing <code>{filename}</code>…",
        "ru": "⏳ Обработка <code>{filename}</code>…",
        "es": "⏳ Procesando <code>{filename}</code>…",
        "de": "⏳ Verarbeitung <code>{filename}</code>…",
        "fr": "⏳ Traitement de <code>{filename}</code>…",
        "zh": "⏳ 正在处理 <code>{filename}</code>…",
        "pt": "⏳ Processando <code>{filename}</code>…",
    },
    "indexed": {
        "en": "✅ Indexed <code>{filename}</code>\n{chunk_count} chunks · ready for queries",
        "ru": "✅ Проиндексирован <code>{filename}</code>\n{chunk_count} фрагментов · готов к запросам",
        "es": "✅ Indexado <code>{filename}</code>\n{chunk_count} fragmentos · listo para consultas",
        "de": "✅ Indexiert <code>{filename}</code>\n{chunk_count} Abschnitte · bereit für Anfragen",
        "fr": "✅ Indexé <code>{filename}</code>\n{chunk_count} fragments · prêt pour les requêtes",
        "zh": "✅ 已索引 <code>{filename}</code>\n{chunk_count} 个片段 · 可用于查询",
        "pt": "✅ Indexado <code>{filename}</code>\n{chunk_count} trechos · pronto para consultas",
    },
    "upload_error": {
        "en": "❌ <code>{filename}</code>\n{error_reason}",
        "ru": "❌ <code>{filename}</code>\n{error_reason}",
        "es": "❌ <code>{filename}</code>\n{error_reason}",
        "de": "❌ <code>{filename}</code>\n{error_reason}",
        "fr": "❌ <code>{filename}</code>\n{error_reason}",
        "zh": "❌ <code>{filename}</code>\n{error_reason}",
        "pt": "❌ <code>{filename}</code>\n{error_reason}",
    },
    "error_unsupported_format": {
        "en": "Unsupported format. Send PDF, DOCX, or TXT.",
        "ru": "Формат не поддерживается. Отправьте PDF, DOCX или TXT.",
        "es": "Formato no compatible. Envía PDF, DOCX o TXT.",
        "de": "Format nicht unterstützt. Senden Sie PDF, DOCX oder TXT.",
        "fr": "Format non pris en charge. Envoyez PDF, DOCX ou TXT.",
        "zh": "不支持的格式。请发送 PDF、DOCX 或 TXT 文件。",
        "pt": "Formato não suportado. Envie PDF, DOCX ou TXT.",
    },
    "error_no_text": {
        "en": "No extractable text found in this document.",
        "ru": "В документе не найден извлекаемый текст.",
        "es": "No se encontró texto extraíble en este documento.",
        "de": "Kein extrahierbarer Text in diesem Dokument gefunden.",
        "fr": "Aucun texte extractible trouvé dans ce document.",
        "zh": "在此文档中未找到可提取的文本。",
        "pt": "Nenhum texto extraível encontrado neste documento.",
    },
    "error_too_large": {
        "en": "Exceeds {max_file_mb} MB limit.",
        "ru": "Превышен лимит {max_file_mb} МБ.",
        "es": "Supera el límite de {max_file_mb} MB.",
        "de": "Überschreitet das Limit von {max_file_mb} MB.",
        "fr": "Dépasse la limite de {max_file_mb} Mo.",
        "zh": "超过 {max_file_mb} MB 上限。",
        "pt": "Excede o limite de {max_file_mb} MB.",
    },
    "error_empty_file": {
        "en": "The file is empty.",
        "ru": "Файл пустой.",
        "es": "El archivo está vacío.",
        "de": "Die Datei ist leer.",
        "fr": "Le fichier est vide.",
        "zh": "文件为空。",
        "pt": "O arquivo está vazio.",
    },
    "error_too_many_chunks": {
        "en": "Document too large after splitting (cap: {max_chunks_per_doc} chunks).",
        "ru": "Документ слишком большой после разбиения (лимит: {max_chunks_per_doc} фрагментов).",
        "es": "Documento demasiado grande tras la división (límite: {max_chunks_per_doc} fragmentos).",
        "de": "Dokument nach Aufteilung zu groß (Limit: {max_chunks_per_doc} Abschnitte).",
        "fr": "Document trop volumineux après découpage (limite : {max_chunks_per_doc} fragments).",
        "zh": "切分后的文档过大（上限：{max_chunks_per_doc} 个片段）。",
        "pt": "Documento muito grande após a divisão (limite: {max_chunks_per_doc} trechos).",
    },
    "error_too_many_docs": {
        "en": "Document limit reached ({max_docs_per_user}). Delete some via /list or /reset.",
        "ru": "Достигнут лимит документов ({max_docs_per_user}). Удалите часть через /list или /reset.",
        "es": "Límite de documentos alcanzado ({max_docs_per_user}). Elimine algunos vía /list o /reset.",
        "de": "Dokumentlimit erreicht ({max_docs_per_user}). Löschen Sie einige über /list oder /reset.",
        "fr": "Limite de documents atteinte ({max_docs_per_user}). Supprimez-en via /list ou /reset.",
        "zh": "已达到文档上限（{max_docs_per_user}）。请通过 /list 或 /reset 删除部分文档。",
        "pt": "Limite de documentos atingido ({max_docs_per_user}). Exclua alguns via /list ou /reset.",
    },
    "error_zip_bomb": {
        "en": "DOCX archive expands beyond the safety limit.",
        "ru": "DOCX-архив превышает безопасный размер при распаковке.",
        "es": "El archivo DOCX se expande más allá del límite de seguridad.",
        "de": "Das DOCX-Archiv überschreitet das Sicherheitslimit beim Entpacken.",
        "fr": "L'archive DOCX dépasse la limite de sécurité au décompactage.",
        "zh": "DOCX 压缩包解压后超过安全上限。",
        "pt": "O arquivo DOCX se expande além do limite de segurança.",
    },
    "error_corrupt_docx": {
        "en": "The DOCX file is corrupt or not a valid archive.",
        "ru": "DOCX-файл повреждён или не является корректным архивом.",
        "es": "El archivo DOCX está dañado o no es un archivo válido.",
        "de": "Die DOCX-Datei ist beschädigt oder kein gültiges Archiv.",
        "fr": "Le fichier DOCX est corrompu ou n'est pas une archive valide.",
        "zh": "DOCX 文件已损坏或不是有效的压缩包。",
        "pt": "O arquivo DOCX está corrompido ou não é um arquivo válido.",
    },
    "answer_message": {
        "en": "<b>Answer</b>\n{answer}\n\n<blockquote expandable><b>Sources</b>\n{sources}\n</blockquote>",
        "ru": "<b>Ответ</b>\n{answer}\n\n<blockquote expandable><b>Источники</b>\n{sources}\n</blockquote>",
        "es": "<b>Respuesta</b>\n{answer}\n\n<blockquote expandable><b>Fuentes</b>\n{sources}\n</blockquote>",
        "de": "<b>Antwort</b>\n{answer}\n\n<blockquote expandable><b>Quellen</b>\n{sources}\n</blockquote>",
        "fr": "<b>Réponse</b>\n{answer}\n\n<blockquote expandable><b>Sources</b>\n{sources}\n</blockquote>",
        "zh": "<b>回答</b>\n{answer}\n\n<blockquote expandable><b>来源</b>\n{sources}\n</blockquote>",
        "pt": "<b>Resposta</b>\n{answer}\n\n<blockquote expandable><b>Fontes</b>\n{sources}\n</blockquote>",
    },
    "answer_not_found": {
        "en": "<i>I could not find this in your documents.</i>",
        "ru": "<i>Не удалось найти это в ваших документах.</i>",
        "es": "<i>No encontré esto en tus documentos.</i>",
        "de": "<i>Konnte dies in Ihren Dokumenten nicht finden.</i>",
        "fr": "<i>Je n'ai pas trouvé cela dans vos documents.</i>",
        "zh": "<i>未能在您的文档中找到相关内容。</i>",
        "pt": "<i>Não encontrei isto nos seus documentos.</i>",
    },
    "source_line": {
        "en": "[{number}] <code>{filename}</code> · chunk {idx}\n↳ <i>{preview}</i>",
        "ru": "[{number}] <code>{filename}</code> · фрагмент {idx}\n↳ <i>{preview}</i>",
        "es": "[{number}] <code>{filename}</code> · fragmento {idx}\n↳ <i>{preview}</i>",
        "de": "[{number}] <code>{filename}</code> · Abschnitt {idx}\n↳ <i>{preview}</i>",
        "fr": "[{number}] <code>{filename}</code> · fragment {idx}\n↳ <i>{preview}</i>",
        "zh": "[{number}] <code>{filename}</code> · 片段 {idx}\n↳ <i>{preview}</i>",
        "pt": "[{number}] <code>{filename}</code> · trecho {idx}\n↳ <i>{preview}</i>",
    },
    "rate_limited": {
        "en": "⚠️ The free language model is currently rate-limited.\n\nPlease retry in a moment, or set your own OpenRouter API key for higher limits.",
        "ru": "⚠️ Бесплатный лимит языковой модели исчерпан.\n\nПовторите запрос через минуту или укажите собственный ключ OpenRouter для более высоких лимитов.",
        "es": "⚠️ El modelo gratuito está actualmente limitado por tasa.\n\nReintente en un momento, o configure su propia clave de OpenRouter para límites más altos.",
        "de": "⚠️ Das kostenlose Sprachmodell ist derzeit ratenbegrenzt.\n\nVersuchen Sie es gleich erneut oder hinterlegen Sie einen eigenen OpenRouter-API-Schlüssel für höhere Limits.",
        "fr": "⚠️ Le modèle gratuit est actuellement limité en débit.\n\nRéessayez dans un instant, ou configurez votre propre clé OpenRouter pour des limites plus élevées.",
        "zh": "⚠️ 免费语言模型当前受到速率限制。\n\n请稍后重试，或配置您自己的 OpenRouter API 密钥以获得更高的限额。",
        "pt": "⚠️ O modelo gratuito está atualmente limitado por taxa.\n\nTente novamente em um momento, ou configure sua própria chave OpenRouter para limites mais altos.",
    },
    "list_empty": {
        "en": "<b>Your documents</b>\n\n<i>No documents yet. Send a file to get started.</i>",
        "ru": "<b>Ваши документы</b>\n\n<i>Документов пока нет. Отправьте файл, чтобы начать.</i>",
        "es": "<b>Tus documentos</b>\n\n<i>Aún no hay documentos. Envía un archivo para comenzar.</i>",
        "de": "<b>Ihre Dokumente</b>\n\n<i>Noch keine Dokumente. Senden Sie eine Datei, um zu beginnen.</i>",
        "fr": "<b>Vos documents</b>\n\n<i>Aucun document pour le moment. Envoyez un fichier pour commencer.</i>",
        "zh": "<b>您的文档</b>\n\n<i>暂无文档。请发送文件以开始。</i>",
        "pt": "<b>Seus documentos</b>\n\n<i>Ainda sem documentos. Envie um arquivo para começar.</i>",
    },
    "list_header": {
        "en": "<b>Your documents</b>",
        "ru": "<b>Ваши документы</b>",
        "es": "<b>Tus documentos</b>",
        "de": "<b>Ihre Dokumente</b>",
        "fr": "<b>Vos documents</b>",
        "zh": "<b>您的文档</b>",
        "pt": "<b>Seus documentos</b>",
    },
    "list_item": {
        "en": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} chunks</i>",
        "ru": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} фрагментов</i>",
        "es": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} fragmentos</i>",
        "de": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} Abschnitte</i>",
        "fr": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} fragments</i>",
        "zh": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} 个片段</i>",
        "pt": "<b>{number}.</b> <code>{filename}</code>\n   <i>{date} · {chunk_count} trechos</i>",
    },
    "settings": {
        "en": "<b>Settings</b>\n\nLanguage: <b>{locale_name}</b>\nDocuments: <b>{doc_count}</b>\nChunks: <b>{chunk_count}</b>",
        "ru": "<b>Настройки</b>\n\nЯзык: <b>{locale_name}</b>\nДокументы: <b>{doc_count}</b>\nФрагменты: <b>{chunk_count}</b>",
        "es": "<b>Configuración</b>\n\nIdioma: <b>{locale_name}</b>\nDocumentos: <b>{doc_count}</b>\nFragmentos: <b>{chunk_count}</b>",
        "de": "<b>Einstellungen</b>\n\nSprache: <b>{locale_name}</b>\nDokumente: <b>{doc_count}</b>\nAbschnitte: <b>{chunk_count}</b>",
        "fr": "<b>Paramètres</b>\n\nLangue : <b>{locale_name}</b>\nDocuments : <b>{doc_count}</b>\nFragments : <b>{chunk_count}</b>",
        "zh": "<b>设置</b>\n\n语言：<b>{locale_name}</b>\n文档数：<b>{doc_count}</b>\n片段数：<b>{chunk_count}</b>",
        "pt": "<b>Configurações</b>\n\nIdioma: <b>{locale_name}</b>\nDocumentos: <b>{doc_count}</b>\nTrechos: <b>{chunk_count}</b>",
    },
    "reset_confirm": {
        "en": "<b>Delete all your data?</b>\n\nThis removes {doc_count} documents and {chunk_count} chunks. The action cannot be undone.",
        "ru": "<b>Удалить все ваши данные?</b>\n\nБудет удалено документов: {doc_count}, фрагментов: {chunk_count}. Действие нельзя отменить.",
        "es": "<b>¿Eliminar todos tus datos?</b>\n\nSe eliminarán {doc_count} documentos y {chunk_count} fragmentos. La acción no se puede deshacer.",
        "de": "<b>Alle Daten löschen?</b>\n\nEs werden {doc_count} Dokumente und {chunk_count} Abschnitte entfernt. Die Aktion kann nicht rückgängig gemacht werden.",
        "fr": "<b>Supprimer toutes vos données ?</b>\n\nCela supprimera {doc_count} documents et {chunk_count} fragments. L'action est irréversible.",
        "zh": "<b>删除您的全部数据？</b>\n\n将删除 {doc_count} 个文档和 {chunk_count} 个片段。此操作无法撤销。",
        "pt": "<b>Excluir todos os seus dados?</b>\n\nIsto removerá {doc_count} documentos e {chunk_count} trechos. A ação não pode ser desfeita.",
    },
    "reset_done": {
        "en": "✅ All data removed.",
        "ru": "✅ Все данные удалены.",
        "es": "✅ Todos los datos eliminados.",
        "de": "✅ Alle Daten entfernt.",
        "fr": "✅ Toutes les données supprimées.",
        "zh": "✅ 所有数据已删除。",
        "pt": "✅ Todos os dados removidos.",
    },
    "delete_confirm": {
        "en": "<b>Delete this document?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} chunks</i>",
        "ru": "<b>Удалить этот документ?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} фрагментов</i>",
        "es": "<b>¿Eliminar este documento?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} fragmentos</i>",
        "de": "<b>Dieses Dokument löschen?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} Abschnitte</i>",
        "fr": "<b>Supprimer ce document ?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} fragments</i>",
        "zh": "<b>删除此文档？</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} 个片段</i>",
        "pt": "<b>Excluir este documento?</b>\n\n<code>{filename}</code>\n<i>{date} · {chunk_count} trechos</i>",
    },
    # locale_name_<code>: the display name of locale <code> when the UI is in the outer locale
    "locale_name_en": {
        "en": "English", "ru": "Английский", "es": "Inglés", "de": "Englisch",
        "fr": "Anglais", "zh": "英语", "pt": "Inglês",
    },
    "locale_name_ru": {
        "en": "Russian", "ru": "Русский", "es": "Ruso", "de": "Russisch",
        "fr": "Russe", "zh": "俄语", "pt": "Russo",
    },
    "locale_name_es": {
        "en": "Spanish", "ru": "Испанский", "es": "Español", "de": "Spanisch",
        "fr": "Espagnol", "zh": "西班牙语", "pt": "Espanhol",
    },
    "locale_name_de": {
        "en": "German", "ru": "Немецкий", "es": "Alemán", "de": "Deutsch",
        "fr": "Allemand", "zh": "德语", "pt": "Alemão",
    },
    "locale_name_fr": {
        "en": "French", "ru": "Французский", "es": "Francés", "de": "Französisch",
        "fr": "Français", "zh": "法语", "pt": "Francês",
    },
    "locale_name_zh": {
        "en": "Chinese", "ru": "Китайский", "es": "Chino", "de": "Chinesisch",
        "fr": "Chinois", "zh": "中文", "pt": "Chinês",
    },
    "locale_name_pt": {
        "en": "Portuguese", "ru": "Португальский", "es": "Portugués", "de": "Portugiesisch",
        "fr": "Portugais", "zh": "葡萄牙语", "pt": "Português",
    },
    # Language buttons — always show the language's NATIVE name with its flag.
    "button_english": {
        "en": "🇬🇧 English", "ru": "🇬🇧 English", "es": "🇬🇧 English", "de": "🇬🇧 English",
        "fr": "🇬🇧 English", "zh": "🇬🇧 English", "pt": "🇬🇧 English",
    },
    "button_russian": {
        "en": "🇷🇺 Русский", "ru": "🇷🇺 Русский", "es": "🇷🇺 Русский", "de": "🇷🇺 Русский",
        "fr": "🇷🇺 Русский", "zh": "🇷🇺 Русский", "pt": "🇷🇺 Русский",
    },
    "button_spanish": {
        "en": "🇪🇸 Español", "ru": "🇪🇸 Español", "es": "🇪🇸 Español", "de": "🇪🇸 Español",
        "fr": "🇪🇸 Español", "zh": "🇪🇸 Español", "pt": "🇪🇸 Español",
    },
    "button_german": {
        "en": "🇩🇪 Deutsch", "ru": "🇩🇪 Deutsch", "es": "🇩🇪 Deutsch", "de": "🇩🇪 Deutsch",
        "fr": "🇩🇪 Deutsch", "zh": "🇩🇪 Deutsch", "pt": "🇩🇪 Deutsch",
    },
    "button_french": {
        "en": "🇫🇷 Français", "ru": "🇫🇷 Français", "es": "🇫🇷 Français", "de": "🇫🇷 Français",
        "fr": "🇫🇷 Français", "zh": "🇫🇷 Français", "pt": "🇫🇷 Français",
    },
    "button_chinese": {
        "en": "🇨🇳 中文", "ru": "🇨🇳 中文", "es": "🇨🇳 中文", "de": "🇨🇳 中文",
        "fr": "🇨🇳 中文", "zh": "🇨🇳 中文", "pt": "🇨🇳 中文",
    },
    "button_portuguese": {
        "en": "🇵🇹 Português", "ru": "🇵🇹 Português", "es": "🇵🇹 Português", "de": "🇵🇹 Português",
        "fr": "🇵🇹 Português", "zh": "🇵🇹 Português", "pt": "🇵🇹 Português",
    },
    "button_settings": {
        "en": "Settings", "ru": "Настройки", "es": "Configuración", "de": "Einstellungen",
        "fr": "Paramètres", "zh": "设置", "pt": "Configurações",
    },
    "button_privacy": {
        "en": "Privacy", "ru": "Приватность", "es": "Privacy", "de": "Privacy",
        "fr": "Privacy", "zh": "Privacy", "pt": "Privacy",
    },
    "button_brief": {
        "en": "Brief", "ru": "Бриф", "es": "Brief", "de": "Brief",
        "fr": "Brief", "zh": "Brief", "pt": "Brief",
    },
    "button_faq": {
        "en": "FAQ", "ru": "FAQ", "es": "FAQ", "de": "FAQ",
        "fr": "FAQ", "zh": "FAQ", "pt": "FAQ",
    },
    "button_quiz": {
        "en": "Quiz", "ru": "Тест", "es": "Quiz", "de": "Quiz",
        "fr": "Quiz", "zh": "Quiz", "pt": "Quiz",
    },
    "button_mindmap": {
        "en": "Mind map", "ru": "Карта тем", "es": "Mind map", "de": "Mind map",
        "fr": "Mind map", "zh": "Mind map", "pt": "Mind map",
    },
    "button_next_question": {
        "en": "Next question", "ru": "Следующий вопрос", "es": "Next question", "de": "Next question",
        "fr": "Next question", "zh": "Next question", "pt": "Next question",
    },
    "button_delete_all": {
        "en": "Delete all data", "ru": "Удалить все данные", "es": "Eliminar todos los datos",
        "de": "Alle Daten löschen", "fr": "Supprimer toutes les données",
        "zh": "删除所有数据", "pt": "Excluir todos os dados",
    },
    "button_close": {
        "en": "Close", "ru": "Закрыть", "es": "Cerrar", "de": "Schließen",
        "fr": "Fermer", "zh": "关闭", "pt": "Fechar",
    },
    "button_yes_delete": {
        "en": "Yes, delete everything", "ru": "Да, удалить всё",
        "es": "Sí, eliminar todo", "de": "Ja, alles löschen",
        "fr": "Oui, tout supprimer", "zh": "是，全部删除",
        "pt": "Sim, excluir tudo",
    },
    "button_cancel": {
        "en": "Cancel", "ru": "Отмена", "es": "Cancelar", "de": "Abbrechen",
        "fr": "Annuler", "zh": "取消", "pt": "Cancelar",
    },
    "button_delete_document": {
        "en": "🗑 {filename}", "ru": "🗑 {filename}", "es": "🗑 {filename}",
        "de": "🗑 {filename}", "fr": "🗑 {filename}", "zh": "🗑 {filename}",
        "pt": "🗑 {filename}",
    },
    "button_confirm": {
        "en": "Confirm", "ru": "Подтвердить", "es": "Confirmar", "de": "Bestätigen",
        "fr": "Confirmer", "zh": "确认", "pt": "Confirmar",
    },
    "default_filename": {
        "en": "document", "ru": "document", "es": "document", "de": "document",
        "fr": "document", "zh": "document", "pt": "document",
    },
}


def t(key: str, locale: str = DEFAULT_LOCALE, **kwargs) -> str:
    """Lookup a string for a locale. Substitute kwargs via str.format."""
    template = (
        STRINGS.get(key, {}).get(locale)
        or STRINGS.get(key, {}).get(DEFAULT_LOCALE)
        or key
    )
    if kwargs:
        return template.format(**kwargs)
    return template
